package com.abhi.edu.mongodb.week2.create;

import java.util.Arrays;

import org.bson.Document;

import com.abhi.edu.mongodb.util.MongoDBUtil;
import com.mongodb.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;

/**
 * Defines the various ways we can create a document in collection of a database
 * @author abhishekkhare
 *
 */
public class InsertTest {

	public static void main(String[] args) {
		inserOne();
		insertMany();
		insertManyWithCustomID();
		System.out.println("DONE");
	}

	/**
	 * Shows how we can insert a single document to a collection. note the Java
	 * Driver inserted the _id for us in the document
	 * 
	 * Query::
	 * db.insertTest.insertOne({ "name" : "Sau", "age" : 35, "profession" : "architect"})
	 */
	private static void inserOne() {
		MongoClient client = new MongoClient();
		MongoDatabase db = client.getDatabase("office");
		MongoCollection<Document> collection = db.getCollection("insertTest");
		collection.drop();
		Document sau = new Document("name", "Sau").append("age", 35).append("profession", "architect");
		collection.insertOne(sau);
		client.close();
		MongoDBUtil.printAllDataFromTable("office", "insertTest");
		// note the Java Driver inserted the _id for us in the document

	}

	/**
	 * Shows how we can insert a single document to a collection. note the Java
	 * Driver inserted the _id for us in the document
	 * 
	 * Query::
	 * db.insertTest.insert({ "name" : "Abhi", "age" : 35, "profession" : "developer"})
	 * db.insertTest.insert({ "name" : "Roop", "age" : 35, "profession" : "hacker"})
	 * db.insertTest.insert({ "name" : "Sau", "age" : 35, "profession" : "architect"})
	 * 
	 * db.insertTest.insert(
	 * 	[
	 * 		{"name" : "Abhi", "age" : 35, "profession" : "developer"},
	 * 		{"name" : "Roop", "age" : 36, "profession" : "hacker"},
	 * 		{ "name" : "Sau", "age" : 35, "profession" : "architect"}
	 * 	]
	 * )
	 * or
	 * db.insertTest.insertMany(
	 * 	[
	 * 		{"name" : "Abhi", "age" : 35, "profession" : "developer"},
	 * 		{"name" : "Roop", "age" : 36, "profession" : "hacker"},
	 * 		{ "name" : "Sau", "age" : 35, "profession" : "architect"}
	 * 	]
	 * )
	 * 
	 * db.insertTest.find()
	 * { "_id" : ObjectId("5785b8b368fd569637cc3a3b"), "name" : "Abhi", "age" : 35, "profession" : "developer" }
	 * { "_id" : ObjectId("5785b8b368fd569637cc3a3c"), "name" : "Roop", "age" : 36, "profession" : "hacker" }
	 * { "_id" : ObjectId("5785b8b368fd569637cc3a3d"), "name" : "Sau", "age" : 35, "profession" : "architect" }
	 * 
	 * Note here we have not provided the _id, here the _id field will be generated by MongoDB.
	 */
	private static void insertMany() {
		MongoClient client = new MongoClient();
		MongoDatabase db = client.getDatabase("office");
		MongoCollection<Document> collection = db.getCollection("insertTest");
		collection.drop();
		Document abhi = new Document("name", "Abhi").append("age", 35).append("profession", "developer");
		Document roop = new Document("name", "Roop").append("age", 36).append("profession", "hacker");
		Document sau = new Document("name", "Sau").append("age", 35).append("profession", "architect");
		collection.insertMany(Arrays.asList(abhi, roop, sau));
		client.close();
		MongoDBUtil.printAllDataFromTable("office", "insertTest");

	}

	/**
	 * Shows how we can insert a multiple document to a collection. With custom id provided by us and not the driver.
	 * Query:
	 * Insert multiple documents, with multiple insert statements.  
	 * 
	 * db.insertTest.insertOne({"_id" : "1", "name" : "Abhi", "age" : 35, "profession" : "developer"})
	 * db.insertTest.insertOne({ "_id" : "2", "name" : "Roop", "age" : 36, "profession" : "hacker" })
	 * 
	 * 
	 * Insert multiple with one insert statements. Please note, that multiple documents are represented here as an Array.
	 * db.insertTest.insert(
	 * 	[
	 * 		{"_id" : "1", "name" : "Abhi", "age" : 35, "profession" : "developer"},
	 * 		{ "_id" : "2", "name" : "Roop", "age" : 36, "profession" : "hacker" }
	 * 	]
	 * )
	 * 
	 */
	private static void insertManyWithCustomID() {
		MongoClient client = new MongoClient();
		MongoDatabase db = client.getDatabase("office");
		MongoCollection<Document> collection = db.getCollection("insertTest");
		collection.drop();
		Document abhi = new Document("name", "Abhi").append("_id", "1").append("age", 35).append("profession",
				"developer");
		Document roop = new Document("name", "Roop").append("_id", "2").append("age", 36).append("profession",
				"hacker");
		collection.insertMany(Arrays.asList(abhi, roop));
		client.close();
		MongoDBUtil.printAllDataFromTable("office", "insertTest");

	}
}
